{% set name = "napari-layer-details-display" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-layer-details-display-{{ version }}.tar.gz
  sha256: 796d6b50933b611ac5a7a9a8c2555c2677d26ba8c9eb87d7a2d105ab8a859c41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >=3.7

test:
  imports:
    - napari_layer_details_display
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-layer-details-display
  summary: A display for layer information and properties
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
